import Header from "@/components/home/Header";
import Head from "next/head";

const Home = () => (
  <>
    <nav className="flex justify-between items-center py-4">
      <div className="flex items-center">
        <img
          aria-hidden="true"
          alt="logo"
          src="https://placehold.co/40x40"
          className="h-8 w-8 mr-2"
        />
        <h1 className="text-lg font-bold">Landing Page</h1>
      </div>
      <div className="flex items-center">
        <input
          type="search"
          className="bg-zinc-200 py-2 px-4 rounded-lg"
          placeholder="Search"
        />
        <img
          aria-hidden="true"
          alt="profile"
          src="https://placehold.co/40x40"
          className="h-8 w-8 ml-4 rounded-full"
        />
      </div>
    </nav>
    <div className="flex min-h-screen mt-12">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Sidebar /> */}
      <div className="flex-1 flex flex-col">
        <Header />
        {/* <MainContent /> */}
      </div>
    </div>
  </>
);

export default Home;
